#!/bin/bash
#
# Copyright 2015, Alexander Jackson <alexander.jackson@seafile.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Uncomment to run in verbose mode
#set -x

# Color coding error messages
PRNTF_FAIL_START="\n\e[1;31m"
PRNTF_FAIL_END="\033[0m"
PRNTF_USAGE_START="\n\e[1;32m"
PRNTF_USAGE_END="\033[0m\n\n"


# Load configuration
PERMS=$(stat ~/.seafile-manager-conf | sed -n '/^Access: (/{s/Access: (\([0-9]\+\).*$/\1/;p}')
if [[ ${PERMS} != 0400 ]]; then echo Permission error. Change form ${PERMS} to 0400 on ~/.seafile-manager-conf and try again.; exit; else . ~/.seafile-manager-conf; fi


# Load functions
. /opt/seafile-manager/inc/account.function
#. /opt/seafile-manager/inc/avatar.function
#. /opt/seafile-manager/inc/batch.function
#. /opt/seafile-manager/inc/blocks.function
#. /opt/seafile-manager/inc/directory.function
#. /opt/seafile-manager/inc/file-activities.function
#. /opt/seafile-manager/inc/file.function
#. /opt/seafile-manager/inc/group-and-contacts.function
#. /opt/seafile-manager/inc/group.function
#. /opt/seafile-manager/inc/library.function
#. /opt/seafile-manager/inc/organizations.function
#. /opt/seafile-manager/inc/server.function
#. /opt/seafile-manager/inc/shared-library.function
#. /opt/seafile-manager/inc/shared-link.function
#. /opt/seafile-manager/inc/star.function
#. /opt/seafile-manager/inc/thumbnail.function
. /opt/seafile-manager/inc/tools.function
#. /opt/seafile-manager/inc/upload-file.function


# Cases
(
case "$1" in

 get-account-info)
        USAGE="Usage: ${0} get-account-info foo@foo.com"
        if [ -z ${2+x} ]; then printf "${PRNTF_FAIL_START}Error: Account email is missing.${PRNTF_FAIL_END}${PRNTF_USAGE_START}${USAGE}${PRNTF_USAGE_END}"; exit ; fi
        echo ${TIMESTAMP}: ${0} get-account-info ${2}
        get-account-info ${2}
        ;;

 check-account-info)
        USAGE="Usage: ${0} check-account-info"
        echo ${TIMESTAMP}: ${0} check-account-info
        check-account-info
        ;;

 create-account)
        USAGE="Usage: ${0} create-account foo@foo.com secret-password"
        if [ -z ${2+x} ]; then echo "Account email is missing."; echo "${USAGE}"; exit; fi
        if [ -z ${3+x} ]; then echo "Password is missing."; echo "${USAGE}"; exit; fi
        echo ${TIMESTAMP}: ${0} create-account ${2} ${3}
        create-account ${2} ${3}
        ;;

 update-password)
        USAGE="Usage: ${0} update-password foo@foo.com secret-password"
        if [ -z ${2+x} ]; then echo "Account email missing."; echo "${USAGE}"; exit; fi
        if [ -z ${3+x} ]; then echo "Password is missing."; echo "${USAGE}"; exit; fi
        echo ${TIMESTAMP}: ${0} update-password ${2} ${3}
        update-password ${2} ${3}
        ;;

 enable-admin)
        USAGE="Usage: ${0} enable-admin foo@foo.com"
        if [ -z ${2+x} ]; then echo "Account email missing."; echo "${USAGE}"; exit; fi
        echo ${TIMESTAMP}: ${0} enable-admin ${2}
        enable-admin ${2}
        ;;

 disable-admin)
        USAGE="Usage: ${0} disable-admin foo@foo.com"
        if [ -z ${2+x} ]; then echo "Account email missing."; echo "${USAGE}"; exit; fi
        echo ${TIMESTAMP}: ${0} disable-admin ${2}
        disable-admin ${2}
        ;;

 activate-account)
       USAGE="Usage: ${0} activate-account foo@foo.com"
       if [ -z ${2+x} ]; then echo "Account email missing."; echo "${USAGE}"; exit; fi
       echo ${TIMESTAMP}: ${0} activate-account ${2}
       activate-account ${2}
       ;;

 deactivate-account)
      USAGE="Usage: ${0} deactivate-account foo@foo.com"
      if [ -z ${2+x} ]; then echo "Account email missing."; echo "${USAGE}"; exit; fi
      echo ${TIMESTAMP}: ${0} deactivate-account ${2}
      deactivate-account ${2}
      ;;

 backup-database)
       echo ${TIMESTAMP}: ${0} backup-seafile
       backup-seafile
       ;;

 *)
        echo "Usage: ${0} { get-account-info | check-account-info | create-account | update-password | enable-admin | disable-admin | activate-account | deactivate-account | backup-database }"
        exit 2
        ;;
esac
) 2>&1 | tee -a ~/$(basename ${0}_${ADDRESS}).log
chmod 600 ~/$(basename ${0}_${ADDRESS}).log
