#!/bin/bash
#
# Copyright 2015, Alexander Jackson <alexander.jackson@seafile.de>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Uncomment to run in verbose mode
#set -x

# Warning
echo "Stop fooling around. You might seriously break something!"

# Comment the next line if you trust this script. ;-)
exit

for i in ../inc/*.function ; do echo -e "\n\n" ; echo $(echo ${i} | sed 's/-/ /g ; s/.function//g ; s/..\/inc\///g ; s/\b\(.\)/\u\1/g') ; echo ------------------------------------------------------------------------; grep -i function ${i} | sed 's/function // ; s/ {// ;  s/.*://' | sort | xargs -n 4 | sed 's/ / | /g' ; done

echo
echo Use these strings in ../seafile-manager
echo
echo ${USAGE}
echo
